modLoader="javafml"
loaderVersion="[43,)"
license="Academic Free License v3.0"

[[mods]]
modId="createarmory"
version="0.5"
displayName="CreateArmory"
credits="dcchill"
displayURL="https://discord.gg/Exw2ZKwW"
logoFile="logo.png"
authors="dcchill"
description='''
Create Armory adds new weapons based on real life and ficitonal firearams
'''

[[dependencies.createarmory]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"



[[dependencies.createarmory]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.createarmory]]
    modId="allmods"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

